### ISSUE TITLE
Random integers in range [0,1)

### ISSUE THREAD

**Issue by tbeu** [lemire/simple_fastfloat_benchmark#13]
I do not get this line in the example output

https://github.com/lemire/simple_fastfloat_benchmark/blob/8d78fd8a098579303719d825af19513a37a3ffd7/README.md?plain=1#L69

So, basically, its a zero all the time? Or should it be floats instead of integers.

**Comment by lemire** [comment]
Thanks for the comment. The typo was fixed in the README.
