### ISSUE TITLE
add various distributions

### ISSUE THREAD

**Issue by lemire** [lemire/simple_fastfloat_benchmark#2]
Uniformly distributed floats in [0, 1) don't represent typical datasets.

We can look at some other distributions (example from ClickHouse performance tests):
https://github.com/ClickHouse/ClickHouse/blob/master/tests/performance/float_parsing.xml

Clarifications about this perf test:
rand() is uniformly distributed UInt32;
rand64() is uniformly distributed UInt64;
In rand(1) and rand(2) the arguments are just tags to distinguish function calls, they behave in the same way as rand().

author of issue @alexey-milovidov 

Recopied from https://github.com/lemire/fast_float/issues/22

**Comment by lemire** [comment]
Ping  @alexey-milovidov

**Comment by lemire** [comment]
> Uniformly distributed floats in [0, 1) don't represent typical datasets.


I agree btw. The tool in this repository allow you to process more realistic data, please see the README.md at https://github.com/lemire/simple_fastfloat_benchmark but using more diverse synthetic data is a great idea.


Thanks for the issue.

**Comment by lemire** [comment]
@alexey-milovidov Some of your generators generate long strings spanning much more than 19 digits. Though I will include them, be mindful of the fact that there is no reason to ever use more than 17 digits, let alone much more than 19.

The fast_float library is not currently well optimized for these cases, and I don't think anyone should serialize numbers using more than 17 digits in the mantissa.

This being said, I have a separate branch where I am working on an optimization. It is rather simple and I expect good results, but it has not been a priority.

**Comment by alexey-milovidov** [comment]
> The fast_float library is not currently well optimized for these cases, and I don't think anyone should serialize numbers using more than 17 digits in the mantissa.

That's true, we can safely skip them...

**Comment by lemire** [comment]
> That's true, we can safely skip them...

I am coding them, and in a second pass over the library, I will optimize these cases as well.

**Comment by lemire** [comment]
I have created a pull request which adds @alexey-milovidov 's models. My implementation is no doubt different, but it should be equivalent.

This is no doubt interesting and useful.

@alexey-milovidov  Could you have a look at the new code?
