### ISSUE TITLE
typos in article

### ISSUE THREAD

**Issue by jftuga** [lemire/simple_fastfloat_benchmark#4]
https://lemire.me/blog/2020/12/11/arm-macbook-vs-intel-macbook/

* In my basic tests, I `general` random floating-point numbers in the unit interval (0,1) and I parse them back exactly. 
* The decimal `significand` spans 17 digits.

**Comment by lemire** [comment]
I corrected "general", as it was pointed out to me.

[Significand is the correct spelling](https://en.wikipedia.org/wiki/Significand), I believe.

**Comment by lemire** [comment]
Thank you.
