### ISSUE TITLE
add ryu's s2d

### ISSUE THREAD

**Issue by Artoria2e5** [lemire/simple_fastfloat_benchmark#7]
[Ryu](https://github.com/ulfjack/ryu) has an pretty incomplete, but probably interesting double parser built using the same principle of their float-to-decimal algorithm. The header can be found in `ryu/ryu_parse.h`. The idea is mentioned in https://dl.acm.org/doi/10.1145/3360595, although at the time of that paper there was not yet an implementation.

Again, it *is* incomplete, so the testing suite might need to be filtered down to remove the failures.

**Comment by lemire** [comment]
@Artoria2e5 Are you willing to add this feature as part of a pull request and ensure that it works properly?

**Comment by Artoria2e5** [comment]
Let me try! If I don't open a PR in a week you know I'm, uh, gone.
